-- Starter content: recipes (Georgian + international) and exercises (home + gym)

insert into public.recipes
  (name, name_ka, description, meal_type, cuisine, calories, protein_g, carbs_g, fat_g, allergens, dietary_tags, prep_time_minutes, ingredients, instructions)
values
  ('Chikhirtma (Georgian Chicken Soup)', 'ჩიხირთმა', 'Tangy Georgian chicken soup thickened with egg and lemon.', 'lunch', 'georgian', 420, 32, 18, 24, '{egg}', '{gluten_free}', 45,
    '["chicken thighs","onion","flour","eggs","lemon juice","cilantro","salt"]',
    'Simmer chicken with onion until tender. Whisk eggs with lemon juice and temper with hot broth. Stir back into pot, garnish with cilantro.'),
  ('Lobio (Georgian Bean Stew)', 'ლობიო', 'Slow-cooked kidney bean stew with walnuts and herbs.', 'dinner', 'georgian', 380, 18, 46, 14, '{nuts}', '{vegetarian,vegan,gluten_free}', 50,
    '["kidney beans","onion","walnuts","cilantro","garlic","blue fenugreek","chili"]',
    'Cook beans until soft. Saute onion, stir in crushed walnuts, garlic, and spices. Combine and simmer 10 minutes.'),
  ('Mchadi with Sulguni', 'მჭადი სულგუნით', 'Georgian cornbread served with fresh sulguni cheese.', 'breakfast', 'georgian', 410, 16, 42, 20, '{dairy}', '{vegetarian,gluten_free}', 20,
    '["cornmeal","water","salt","sulguni cheese"]',
    'Mix cornmeal with warm water and salt into a dough. Shape into flat cakes, pan-fry until golden, serve with sliced cheese.'),
  ('Georgian Vegetable Ajapsandali', 'აჯაფსანდალი', 'Eggplant, pepper and tomato stew, a Georgian ratatouille.', 'dinner', 'georgian', 260, 6, 30, 12, '{}', '{vegetarian,vegan,gluten_free,dairy_free}', 40,
    '["eggplant","bell pepper","tomato","onion","garlic","cilantro"]',
    'Saute eggplant and onion, add pepper and tomato, simmer until soft, finish with garlic and herbs.'),
  ('Greek Yogurt Bowl with Walnuts & Honey', 'ბერძნული იოგურტი კაკლით და თაფლით', 'High-protein breakfast bowl with fruit and nuts.', 'breakfast', 'international', 340, 22, 34, 12, '{dairy,nuts}', '{vegetarian,gluten_free}', 5,
    '["greek yogurt","walnuts","honey","berries"]',
    'Spoon yogurt into a bowl, top with berries, walnuts, and a drizzle of honey.'),
  ('Grilled Chicken & Quinoa Bowl', 'გრილზე შემწვარი ქათმის და ქინოას თასი', 'Lean protein bowl with quinoa and roasted vegetables.', 'lunch', 'international', 520, 42, 48, 16, '{}', '{gluten_free,dairy_free}', 30,
    '["chicken breast","quinoa","broccoli","olive oil","lemon"]',
    'Grill seasoned chicken breast. Cook quinoa. Roast broccoli. Combine and dress with olive oil and lemon.'),
  ('Baked Salmon with Sweet Potato', 'გამომცხვარი ორაგული ტკბილი კარტოფილით', 'Omega-3 rich salmon with roasted sweet potato and greens.', 'dinner', 'international', 560, 38, 40, 24, '{fish}', '{gluten_free,dairy_free}', 35,
    '["salmon fillet","sweet potato","olive oil","spinach","garlic"]',
    'Roast sweet potato wedges. Bake salmon at 200C for 12-15 minutes. Saute spinach with garlic. Plate together.'),
  ('Overnight Oats with Banana & Peanut Butter', 'ღამის ოატმილი ბანანით და კარაქით', 'Fiber-rich make-ahead breakfast.', 'breakfast', 'international', 430, 16, 58, 14, '{peanuts}', '{vegetarian}', 10,
    '["rolled oats","milk","banana","peanut butter","chia seeds"]',
    'Combine oats, milk, and chia in a jar. Refrigerate overnight. Top with sliced banana and peanut butter.'),
  ('Turkey & Vegetable Stir-fry', 'ინდაურის შემწვარი ბოსტნეულით', 'Quick high-protein stir-fry with mixed vegetables.', 'dinner', 'international', 480, 40, 32, 18, '{soy}', '{dairy_free}', 25,
    '["ground turkey","bell pepper","broccoli","soy sauce","garlic","ginger","rice"]',
    'Stir-fry turkey until browned. Add vegetables and aromatics. Season with soy sauce, serve over rice.'),
  ('Lentil Soup (Mercimek)', 'ოსპის სუპი', 'Warming red lentil soup, naturally vegan and gluten-free.', 'lunch', 'international', 320, 18, 46, 6, '{}', '{vegetarian,vegan,gluten_free,dairy_free}', 30,
    '["red lentils","onion","carrot","cumin","lemon"]',
    'Saute onion and carrot, add lentils and stock, simmer 20 minutes, blend lightly, finish with lemon and cumin.'),
  ('Khachapuri-style Egg & Cheese Toast (lighter)', 'ხაჭაპურის სტილის ტოსტი', 'A lighter take on Georgian khachapuri flavors on toast.', 'breakfast', 'georgian', 390, 20, 32, 20, '{dairy,egg,gluten}', '{vegetarian}', 12,
    '["whole grain bread","sulguni cheese","egg","butter"]',
    'Toast bread, top with cheese and grill until melted, top with a fried egg.'),
  ('Cottage Cheese & Cucumber Plate', 'რძიანი ხაჭო კიტრით', 'Simple high-protein snack plate.', 'snack', 'international', 220, 24, 10, 8, '{dairy}', '{vegetarian,gluten_free}', 5,
    '["cottage cheese","cucumber","olive oil","dill"]',
    'Plate cottage cheese with sliced cucumber, drizzle olive oil, garnish with dill.'),
  ('Protein Smoothie', 'პროტეინის სმუზი', 'Quick post-workout shake.', 'snack', 'international', 260, 28, 26, 5, '{dairy}', '{vegetarian,gluten_free}', 5,
    '["protein powder","milk","banana","ice"]',
    'Blend all ingredients until smooth.'),
  ('Hummus & Veggie Sticks', 'ჰუმუსი და ბოსტნეული', 'Fiber-rich vegan snack.', 'snack', 'international', 210, 8, 22, 10, '{}', '{vegetarian,vegan,gluten_free,dairy_free}', 5,
    '["chickpeas","tahini","lemon","carrot","celery"]',
    'Blend chickpeas, tahini, and lemon into hummus. Serve with vegetable sticks.'),
  ('Khinkali (Steamed Dumplings, light portion)', 'ხინკალი', 'Traditional Georgian dumplings, portion-controlled.', 'lunch', 'georgian', 480, 22, 50, 20, '{gluten,egg}', '{}', 60,
    '["ground beef and pork","flour","onion","black pepper","water"]',
    'Make dough, fill with seasoned meat mixture, pleat into pouches, boil until floating.'),
  ('Mixed Greens Salad with Grilled Halloumi', 'შერეული სალათი გრილზე შემწვარი ყველით', 'Fresh salad with grilled cheese for protein.', 'lunch', 'international', 400, 20, 18, 28, '{dairy}', '{vegetarian,gluten_free}', 15,
    '["mixed greens","halloumi","cherry tomato","olive oil","balsamic"]',
    'Grill halloumi slices until golden. Toss greens and tomato with olive oil and balsamic, top with halloumi.'),
  ('Edamame with Sea Salt', 'ედამამე მარილით', 'Steamed soybeans, a simple high-protein snack.', 'snack', 'international', 190, 17, 14, 8, '{soy}', '{vegetarian,vegan,gluten_free,dairy_free}', 8,
    '["edamame","sea salt"]',
    'Steam edamame pods 5 minutes, toss with sea salt.'),
  ('Roasted Chickpeas', 'შემწვარი მუხუდო', 'Crunchy oven-roasted chickpeas.', 'snack', 'international', 210, 10, 30, 6, '{}', '{vegetarian,vegan,gluten_free,dairy_free}', 25,
    '["chickpeas","olive oil","paprika","salt"]',
    'Toss drained chickpeas with oil and spices, roast at 200C for 20-25 minutes until crisp.'),
  ('Turkey & Cucumber Roll-ups', 'ინდაურის და კიტრის რულეტები', 'Light high-protein snack, no dairy or gluten.', 'snack', 'international', 180, 22, 4, 8, '{}', '{gluten_free,dairy_free}', 8,
    '["turkey slices","cucumber","mustard"]',
    'Spread mustard on turkey slices, roll around cucumber sticks.'),
  ('Apple with Sunflower Seed Butter', 'ვაშლი მზესუმზირის კარაქით', 'Nut-free, dairy-free fruit and seed-butter snack.', 'snack', 'international', 240, 6, 28, 12, '{}', '{vegetarian,vegan,gluten_free,dairy_free}', 3,
    '["apple","sunflower seed butter"]',
    'Slice apple and serve with sunflower seed butter for dipping.');

insert into public.exercises
  (name, name_ka, muscle_group, equipment, setting, difficulty, instructions, default_sets, default_reps)
values
  ('Bodyweight Squat', 'სხეულის წონით ჩაჯდომა', 'legs', '{bodyweight}', 'both', 'beginner', 'Stand feet shoulder-width apart, lower hips back and down until thighs are parallel to floor, drive back up through heels.', 3, '12-15'),
  ('Push-up', 'წვე-ტეხვა (ფუშაფი)', 'chest', '{bodyweight}', 'both', 'beginner', 'Hands slightly wider than shoulders, lower chest to floor keeping body straight, push back up.', 3, '8-12'),
  ('Walking Lunge', 'სიარულით ლანჟი', 'legs', '{bodyweight}', 'both', 'beginner', 'Step forward into a lunge, lower back knee toward floor, push through front heel to step into next lunge.', 3, '10 per leg'),
  ('Plank', 'პლანკი', 'core', '{bodyweight}', 'both', 'beginner', 'Forearms and toes on floor, body in a straight line from head to heels, brace core and hold.', 3, '30-45s'),
  ('Glute Bridge', 'დუნდულოების ხიდი', 'legs', '{bodyweight}', 'both', 'beginner', 'Lie on back, knees bent, feet flat. Drive hips upward squeezing glutes, lower with control.', 3, '15'),
  ('Mountain Climbers', 'მთამსვლელები', 'cardio', '{bodyweight}', 'both', 'beginner', 'From a plank position, drive knees alternately toward chest at a quick pace.', 3, '30s'),
  ('Superman Hold', 'სუპერმენის დაჭერა', 'back', '{bodyweight}', 'both', 'beginner', 'Lie face down, simultaneously lift arms, chest, and legs off the floor, hold briefly, lower.', 3, '10-12'),
  ('Bicycle Crunch', 'ველოსიპედის ტანვარჯიში', 'core', '{bodyweight}', 'both', 'beginner', 'Lying on back, alternate bringing opposite elbow to opposite knee in a pedaling motion.', 3, '20 total'),
  ('Tricep Dip (chair)', 'ტრიცეფსის დამშვები', 'arms', '{bodyweight,bench}', 'both', 'intermediate', 'Hands on edge of a sturdy chair, lower body by bending elbows, press back up.', 3, '10-12'),
  ('Jumping Jacks', 'ხტუნვა-ტეხვა', 'cardio', '{bodyweight}', 'both', 'beginner', 'Jump feet out while raising arms overhead, jump back to start, repeat at pace.', 3, '45s'),
  ('Dumbbell Goblet Squat', 'გობლეტ ჩაჯდომა ჰანტელით', 'legs', '{dumbbells}', 'both', 'intermediate', 'Hold a dumbbell vertically at chest, squat down keeping chest tall, drive back up.', 4, '10-12'),
  ('Dumbbell Row', 'ჰანტელით ნიჩაბი', 'back', '{dumbbells,bench}', 'both', 'intermediate', 'Hinge at hips, one hand on bench, pull dumbbell to hip keeping elbow close, lower with control.', 4, '10-12 per side'),
  ('Dumbbell Shoulder Press', 'ჰანტელით მხრების პრესი', 'shoulders', '{dumbbells}', 'both', 'intermediate', 'Press dumbbells overhead from shoulder height until arms extend, lower with control.', 3, '10-12'),
  ('Dumbbell Romanian Deadlift', 'რუმინული დედლიფტი ჰანტელით', 'legs', '{dumbbells}', 'both', 'intermediate', 'Hinge at hips keeping back flat, lower dumbbells along legs until hamstring stretch, drive hips forward to stand.', 4, '10-12'),
  ('Barbell Back Squat', 'შტანგით ზურგზე ჩაჯდომა', 'legs', '{barbell,squat_rack}', 'gym', 'advanced', 'Bar on upper back, squat down until hips below knees, drive through heels to stand.', 4, '6-8'),
  ('Barbell Bench Press', 'შტანგის მაგიდის პრესი', 'chest', '{barbell,bench}', 'gym', 'advanced', 'Lower bar to mid-chest with control, press back up to full extension.', 4, '6-8'),
  ('Lat Pulldown Machine', 'ლათ პულდაუნის ტრენაჟორი', 'back', '{machine}', 'gym', 'intermediate', 'Pull bar down to upper chest, squeezing shoulder blades, control the return.', 4, '10-12'),
  ('Leg Press Machine', 'ფეხების პრესის ტრენაჟორი', 'legs', '{machine}', 'gym', 'intermediate', 'Feet shoulder-width on platform, lower until knees at 90 degrees, press back up.', 4, '10-12'),
  ('Cable Tricep Pushdown', 'ტრიცეფსის დაწევა ბლოკზე', 'arms', '{machine}', 'gym', 'beginner', 'Elbows tucked at sides, push bar down to full extension, control the return.', 3, '12-15'),
  ('Seated Cable Row', 'ჯდომით ნიჩაბი ბლოკზე', 'back', '{machine}', 'gym', 'intermediate', 'Pull handle to torso keeping back straight, squeeze shoulder blades, control return.', 4, '10-12'),
  ('Kettlebell Swing', 'გირწონა კეთლბელით', 'full_body', '{kettlebell}', 'both', 'intermediate', 'Hinge at hips and swing kettlebell between legs, drive hips forward to swing to chest height.', 4, '15-20'),
  ('Treadmill Interval Run', 'ინტერვალური სირბილი სავარჯიშო ბილიკზე', 'cardio', '{cardio_machine}', 'gym', 'intermediate', 'Alternate 1 minute fast pace with 2 minutes moderate pace for the set duration.', 1, '20 min'),
  ('Resistance Band Row', 'ნიჩაბი რეზისტენტული ლენტით', 'back', '{resistance_band}', 'home', 'beginner', 'Anchor band, pull handles toward torso squeezing shoulder blades, control return.', 3, '12-15'),
  ('Step-up (chair or bench)', 'ასვლა სკამზე', 'legs', '{bodyweight,bench}', 'both', 'beginner', 'Step fully onto a sturdy platform, drive through the lead heel to stand, step down with control.', 3, '10 per leg'),
  ('Incline Dumbbell Press', 'დახრილი მაგიდის პრესი ჰანტელით', 'chest', '{dumbbells,bench}', 'both', 'intermediate', 'On an inclined bench, press dumbbells up from chest height to full extension, lower with control.', 4, '8-12'),
  ('Cable Chest Fly', 'გულმკერდის ფრენა ბლოკზე', 'chest', '{machine}', 'gym', 'intermediate', 'Stand between cable towers, bring handles together in front of chest in an arcing motion, control the return.', 3, '10-12'),
  ('Dumbbell Lateral Raise', 'გვერდითი აწევა ჰანტელით', 'shoulders', '{dumbbells}', 'both', 'beginner', 'Raise dumbbells out to the sides to shoulder height, lower with control.', 3, '12-15'),
  ('Overhead Barbell Press', 'შტანგის ზედა პრესი', 'shoulders', '{barbell}', 'gym', 'advanced', 'Press barbell from shoulder height overhead to full extension, lower with control.', 4, '6-8'),
  ('Cable Face Pull', 'სახის მიმართულებით მოზიდვა ბლოკზე', 'shoulders', '{machine}', 'gym', 'intermediate', 'Pull rope attachment toward face at eye level, elbows high, squeezing rear shoulders.', 3, '12-15'),
  ('Dumbbell Bicep Curl', 'ბიცეფსის მოხრა ჰანტელით', 'arms', '{dumbbells}', 'both', 'beginner', 'Curl dumbbells toward shoulders keeping elbows fixed at sides, lower with control.', 3, '10-12'),
  ('Russian Twist', 'რუსული ტრიალი', 'core', '{bodyweight}', 'both', 'beginner', 'Seated with feet lifted, rotate torso side to side tapping the floor beside hips.', 3, '20 total');
